### ISSUE TITLE
Your Facebook link is broken

### ISSUE THREAD

**Issue by davidfou** [kspe/ignacy.co#1]
😢

**Comment by davidfou** [comment]
Actually only if I'm not logged in
<img width="604" alt="screen shot 2018-09-06 at 14 46 30" src="https://user-images.githubusercontent.com/2329786/45158231-afcde900-b1e3-11e8-837b-483f93a3f493.png">

**Comment by kspe** [comment]
Thanks for the report, I'm pretty sure it is because of privacy settings as my profile is not visible for non-logged users on FB.

**Comment by davidfou** [comment]
👍
